version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: env
      - run: echo "Installing dependencies"
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: echo "Running tests"
      - run: npm run test-coverage
workflows:
  version: 2
  run_tests:
    jobs:
      - test
